# Generated by Django 3.2.9 on 2021-11-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lista_categoria', '0002_listacategoria_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Lista_Produtos')),
                ('categorias', models.ManyToManyField(to='lista_categoria.ListaCategoria')),
            ],
        ),
    ]
