# Generated by Django 3.2.9 on 2021-11-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacategoria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Lista_Categoria'),
        ),
    ]
